# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='coursetakers',
            field=models.ManyToManyField(related_name='registered_courses', to='login_reg_app.Users'),
        ),
    ]
